# In memory h2 database setup
# with JPA
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console.enabled: true
## setup with file-storage.
#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

